services:
  notifications-service-postgresql:
    image: bitnami/postgresql
    container_name: notifications-service-postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=notifications-service